"""
physics_loss.py  (v2 — fixed lift_consistency_loss)

Physics-informed loss terms for aerodynamic surrogate modeling.
Implements four soft aerodynamic constraints:

  1. Lift-Pressure Consistency  -- ΔCp = Cp_pressure − Cp_suction should
                                   integrate to be consistent with Cl
  2. Pressure Smoothness        -- penalize high-frequency oscillations in Cp
  3. Drag Positivity            -- Cd must be >= 0
  4. Drag Consistency           -- Cd must be >= Cdp (pressure drag component)

BUG FIXED vs v1
---------------
The original lift_consistency_loss integrated the full 98-point Cp array
straight across (treating it as one continuous curve).  That was wrong.

The 98-point Cp array has this exact layout, traced from NASA's
Step4_CreateDataset.py (CreateDatasetFromJson) and ResizeCp.py:

    ResizeCp.py sets cp_points = 50, so each surface has 50 points on a
    uniform x/c grid [0, 1].

    Step4 then concatenates:
        Cp = np.concatenate(( Cp_ss, np.flip(Cp_ps[1:-1]) ))
           = [Cp_suction  (50 pts, x/c = 0→1)]
           + [Cp_pressure (48 pts, x/c = 1→0, endpoints stripped then flipped)]
           = 98 points total

    So:
        pred_cp[:, :50]  → suction side,  x/c = 0 → 1
        pred_cp[:, 50:]  → pressure side, x/c = 1 → 0  (reversed)

Lift is generated by the pressure DIFFERENCE between the two surfaces:
    ΔCp(x) = Cp_pressure(x) − Cp_suction(x)
    Cl ∝ ∫₀¹ ΔCp(x) dx

Integrating the raw concatenated curve adds (instead of subtracts) the two
surface contributions, which is physically wrong and not fixable by a scale
factor.

FIX: split into suction/pressure halves, flip pressure side to 0→1, align
on the 48 shared interior x/c points, compute ΔCp, integrate trapezoidally,
and enforce rank-ordering consistency with pred_cl via normalised MSE
(since data is normalized, the scale of ∫ΔCp dx ≠ scale of Cl in the
normalized space, so we enforce direction/ordering, not exact magnitude).

verify_constraints() is updated consistently to use the same corrected
integral for the lift_cp_correlation metric.

All functions accept PyTorch tensors of shape (batch, ...) and return
scalar losses compatible with autograd / backward().

Usage:
    from physics_loss import PhysicsLoss
    physics = PhysicsLoss(lambda_lift=1.0, lambda_smooth=0.01,
                          lambda_drag=0.1, lambda_cdp=0.1)
    loss_dict = physics(pred, target)
    # loss_dict keys: 'lift', 'smooth', 'drag', 'cdp', 'total'
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Cp layout constants — derived from NASA Step4_CreateDataset.py +
# ResizeCp.py.  Change here if the dataset changes.
# ---------------------------------------------------------------------------
_N_CP_SS = 50   # suction-side points (x/c = 0→1, inclusive)
_N_CP_PS = 48   # pressure-side points after stripping shared endpoints
                # (stored reversed: x/c = 1→0 in the array)
# _N_CP_SS + _N_CP_PS == 98  ✓


def _split_cp(pred_cp):
    """
    Split the 98-point concatenated Cp array into suction and pressure sides,
    both aligned to x/c = 0→1.

    Input:
        pred_cp : (batch, 98)
            [:, :50]  suction side,  x/c = 0→1
            [:, 50:]  pressure side, x/c = 1→0

    Returns:
        cp_ss : (batch, 50) suction side,  x/c = 0→1
        cp_ps : (batch, 48) pressure side, x/c = 0→1  (flipped)

    Note: suction has 50 points (indices 0..49 inclusive across x/c=0..1).
    Pressure has 48 interior points.  For the ΔCp integral we align them
    on the 48 shared interior x/c locations (suction indices 1..48,
    i.e. x/c ≈ 0.0204 .. 0.9796).
    """
    cp_ss = pred_cp[:, :_N_CP_SS]                        # (batch, 50), x/c 0→1
    cp_ps = torch.flip(pred_cp[:, _N_CP_SS:], dims=[1])  # (batch, 48), x/c 0→1
    return cp_ss, cp_ps


def _delta_cp_integral(pred_cp):
    """
    Compute ΔCp = Cp_pressure − Cp_suction and integrate over x/c
    using the trapezoidal rule.

    Alignment: the 48 pressure-side points correspond to the 48 interior
    points of the suction side (suction indices 1..48, skipping the leading-
    and trailing-edge shared nodes that were stripped when building the loop).

        x_interior = linspace(0, 1, 50)[1:-1]   →  48 points
        Δx = 1/49  (spacing between consecutive interior points)

    Returns:
        cl_from_delta_cp : (batch,) — unnormalised surrogate for Cl
    """
    cp_ss, cp_ps = _split_cp(pred_cp)
    cp_ss_inner = cp_ss[:, 1:-1]   # (batch, 48), interior suction points

    delta_cp = cp_ps - cp_ss_inner  # (batch, 48), ΔCp at 48 x/c locations

    # Trapezoidal rule over 48 points → 47 intervals
    dx = 1.0 / 49.0   # uniform spacing on x/c=[0,1] with 50 points → Δx=1/49
    cl_from_cp = 0.5 * (delta_cp[:, :-1] + delta_cp[:, 1:]).sum(dim=1) * dx
    return cl_from_cp                # (batch,)


class PhysicsLoss(nn.Module):
    """
    Combined physics-informed loss for the airfoil surrogate model.

    Args:
        lambda_lift   (float): weight for lift-pressure consistency loss
        lambda_smooth (float): weight for Cp smoothness loss
        lambda_drag   (float): weight for drag positivity loss
        lambda_cdp    (float): weight for drag decomposition consistency loss
        n_cp          (int):   total Cp points; must be 98 for NASA dataset

    Tensor layouts
    --------------
    pred   (batch, 100):  [Cl, Cd, Cp×98]
    target (batch, 102):  [Cl, Cd, Cdp, Cm, Cp×98]
               OR (batch, 100) if Cdp unavailable — set lambda_cdp=0 then
    """

    def __init__(
        self,
        lambda_lift:   float = 1.0,
        lambda_smooth: float = 0.01,
        lambda_drag:   float = 0.1,
        lambda_cdp:    float = 0.1,
        n_cp:          int   = 98,
    ):
        super().__init__()
        if n_cp != 98:
            raise ValueError(
                f"n_cp={n_cp} is unsupported.  The NASA dataset has exactly 98 "
                "Cp points (50 suction + 48 pressure interior).  If you resample "
                "to a different count, update _N_CP_SS and _N_CP_PS accordingly."
            )
        self.lambda_lift   = lambda_lift
        self.lambda_smooth = lambda_smooth
        self.lambda_drag   = lambda_drag
        self.lambda_cdp    = lambda_cdp
        self.n_cp          = n_cp

    # ------------------------------------------------------------------
    # Individual constraint terms
    # ------------------------------------------------------------------

    def lift_consistency_loss(self, pred_cl, pred_cp):
        """
        Constraint: Cl is proportional to ∫₀¹ ΔCp dx,
        where ΔCp = Cp_pressure − Cp_suction.

        Since all values are normalised (independent scalers for Cl and Cp),
        the integral magnitude ≠ Cl magnitude.  We therefore enforce
        rank-ordering/direction consistency via normalised MSE:
        both pred_cl and cl_from_delta_cp are z-scored before the MSE,
        making the loss equivalent to penalising 1 − Pearson_correlation.

        This is the corrected version.  The original (v1) integrated the
        raw 98-point concatenated curve, which sums instead of subtracts
        the two surfaces and does not correspond to any aerodynamic quantity.
        """
        cl_from_cp = _delta_cp_integral(pred_cp)   # (batch,)

        # Z-score normalise both signals independently so scale mismatch
        # from the independent Cl/Cp normalisers doesn't dominate the loss.
        def znorm(t):
            return (t - t.mean()) / (t.std() + 1e-8)

        return F.mse_loss(znorm(pred_cl.squeeze()), znorm(cl_from_cp))

    def smoothness_loss(self, pred_cp):
        """
        Constraint: penalise rapid variation between consecutive Cp points.

            L_smooth = mean[ (Cp[i+1] − Cp[i])² ]

        Applied to the full 98-point concatenated curve.  Note that the
        junction between suction and pressure sides (index 49→50) will
        naturally have a larger difference (the curve reverses direction
        there).  This is a known mild artefact of applying smoothness to
        the concatenated loop rather than each surface separately; in
        practice the junction penalty is small relative to genuine
        high-frequency noise and does not cause problems.

        If it becomes an issue, apply smoothness to each half separately:
            cp_ss, cp_ps = _split_cp(pred_cp)
            loss = smoothness on cp_ss + smoothness on cp_ps
        """
        diff = pred_cp[:, 1:] - pred_cp[:, :-1]   # (batch, 97)
        return (diff ** 2).mean()

    def drag_positivity_loss(self, pred_cd):
        """
        Constraint: Cd >= 0

            L_drag = mean[ ReLU(−Cd) ]

        Zero penalty when Cd >= 0, linear penalty proportional to violation
        magnitude when Cd < 0.
        """
        return torch.relu(-pred_cd).mean()

    def drag_consistency_loss(self, pred_cd, true_cdp):
        """
        Constraint: Cd >= Cdp  (total drag >= pressure drag component)

            L_cdp = mean[ ReLU(Cdp_true − Cd_pred) ]

        Uses ground-truth Cdp since it is not a model output.  Penalises
        predictions where total drag is smaller than the known pressure
        drag component alone.
        """
        return torch.relu(true_cdp - pred_cd).mean()

    # ------------------------------------------------------------------
    # Forward
    # ------------------------------------------------------------------

    def forward(self, pred, target):
        """
        Compute all physics loss terms.

        Args:
            pred   : (batch, 100)  model output  [Cl, Cd, Cp×98]
            target : (batch, 102)  ground truth  [Cl, Cd, Cdp, Cm, Cp×98]
                     OR (batch, 100) — set lambda_cdp=0 if Cdp unavailable

        Returns:
            dict with keys: 'lift', 'smooth', 'drag', 'cdp', 'total'
            All values are scalar tensors; 'total' is the weighted sum
            suitable for loss.backward().
        """
        pred_cl = pred[:, 0]          # (batch,)
        pred_cd = pred[:, 1]          # (batch,)
        pred_cp = pred[:, 2:]         # (batch, 98)

        losses = {}

        # 1. Lift-pressure consistency (corrected)
        losses["lift"] = self.lift_consistency_loss(pred_cl, pred_cp)

        # 2. Smoothness
        losses["smooth"] = self.smoothness_loss(pred_cp)

        # 3. Drag positivity
        losses["drag"] = self.drag_positivity_loss(pred_cd)

        # 4. Drag consistency — requires Cdp in target (102 cols)
        if self.lambda_cdp > 0 and target.shape[1] > 100:
            true_cdp = target[:, 2]   # (batch,)
            losses["cdp"] = self.drag_consistency_loss(pred_cd, true_cdp)
        else:
            losses["cdp"] = torch.tensor(0.0, device=pred.device)

        losses["total"] = (
            self.lambda_lift   * losses["lift"]   +
            self.lambda_smooth * losses["smooth"] +
            self.lambda_drag   * losses["drag"]   +
            self.lambda_cdp    * losses["cdp"]
        )

        return losses


# ---------------------------------------------------------------------------
# Standalone verification (use after training, not during)
# ---------------------------------------------------------------------------

def verify_constraints(pred, target, n_cp=98, verbose=True):
    """
    Check what fraction of predictions satisfy each physical constraint.
    Run this on validation/test predictions after training to confirm the
    physics losses are improving physical consistency, not just loss numbers.

    Args:
        pred   : (batch, 100) model output  [Cl, Cd, Cp×98]
        target : (batch, 102) ground truth  [Cl, Cd, Cdp, Cm, Cp×98]
                 OR (batch, 100) — drag_consistency_rate will be None

    Returns:
        dict of constraint satisfaction metrics

    Metrics
    -------
    drag_positivity_rate   : fraction of samples with Cd >= 0  (target: 1.0)
    drag_consistency_rate  : fraction with Cd >= Cdp_true      (target: 1.0)
    mean_cp_smoothness     : mean squared adjacent-point diff in Cp (lower = smoother)
    lift_cp_correlation    : Pearson r between pred_cl and ∫ΔCp dx  (target: ~1.0)
                             Uses the CORRECTED ΔCp integral (v2).
    """
    if n_cp != 98:
        raise ValueError("verify_constraints expects n_cp=98 (NASA dataset layout).")

    pred_cl = pred[:, 0]
    pred_cd = pred[:, 1]
    pred_cp = pred[:, 2:]

    results = {}

    # --- Drag positivity ---
    drag_ok = (pred_cd >= 0).float().mean().item()
    results["drag_positivity_rate"] = drag_ok

    # --- Drag consistency ---
    if target.shape[1] > 100:
        true_cdp = target[:, 2]
        cdp_ok = (pred_cd >= true_cdp).float().mean().item()
        results["drag_consistency_rate"] = cdp_ok
    else:
        results["drag_consistency_rate"] = None

    # --- Cp smoothness ---
    diff = pred_cp[:, 1:] - pred_cp[:, :-1]
    results["mean_cp_smoothness"] = (diff ** 2).mean().item()

    # --- Lift-Cp correlation (corrected ΔCp integral) ---
    cl_from_cp = _delta_cp_integral(pred_cp)   # (batch,)
    # corrcoef expects (2, N)
    corr_matrix = torch.corrcoef(torch.stack([pred_cl.detach(), cl_from_cp.detach()]))
    corr = corr_matrix[0, 1].item()
    results["lift_cp_correlation"] = corr

    if verbose:
        print("=== Physics Constraint Verification ===")
        print(f"  Drag positivity  (Cd >= 0):        {drag_ok * 100:.1f}% of predictions")
        if results["drag_consistency_rate"] is not None:
            print(f"  Drag consistency (Cd >= Cdp):      {cdp_ok * 100:.1f}% of predictions")
        else:
            print(f"  Drag consistency (Cd >= Cdp):      N/A (Cdp not in target)")
        print(f"  Cp smoothness    (mean sq diff):   {results['mean_cp_smoothness']:.6f}")
        print(f"  Lift-Cp correlation (corrected):   {corr:.4f}")
        print()
        print("  Note: lift_cp_correlation uses ΔCp = Cp_pressure − Cp_suction")
        print("  integrated trapezoidally over x/c=[0,1] (48 interior points).")
        print("  v1 used the raw 98-pt loop integral — that metric is now removed.")

    return results


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    torch.manual_seed(0)
    B = 32

    pred   = torch.randn(B, 100)
    target = torch.randn(B, 102)

    # --- PhysicsLoss forward ---
    physics = PhysicsLoss(lambda_lift=1.0, lambda_smooth=0.01,
                          lambda_drag=0.1, lambda_cdp=0.1)
    losses = physics(pred, target)
    print("PhysicsLoss forward pass:")
    for k, v in losses.items():
        print(f"  {k:10s}: {v.item():.6f}")

    print()

    # --- verify_constraints ---
    verify_constraints(pred, target, n_cp=98, verbose=True)

    print()

    # --- Sanity: perfect prediction should give lift_cp_correlation = 1.0 ---
    # Build a fake pred where Cl IS exactly the ΔCp integral (z-normed)
    cp_ss = torch.zeros(B, 50)
    cp_ps_inner = torch.ones(B, 48)                   # ΔCp = 1 everywhere
    # Build a 98-pt Cp: suction=0, pressure side reversed back
    cp_fake = torch.cat([cp_ss, torch.flip(cp_ps_inner, dims=[1])], dim=1)
    integral = _delta_cp_integral(cp_fake)             # should be ~1.0 per sample
    pred_perfect = torch.cat([
        integral.unsqueeze(1),                         # Cl = integral
        torch.zeros(B, 1),                             # Cd
        cp_fake,                                       # Cp
    ], dim=1)
    results_perfect = verify_constraints(pred_perfect, target, verbose=False)
    print(f"Sanity check — perfect lift correlation: "
          f"{results_perfect['lift_cp_correlation']:.4f}  (expected ~1.0)")
